### PR TITLE
fix invalid locale error

### LINKED ISSUE #62: Warning: invalid local UTF-8 at the end of the `meilisearch-setup` script
**Description**
A Warning message appears at the end of the `meilisearch-setup` script.
The command gives by the warning or an `export` should fix the problem and should be added to the `cloud-config.yaml`.

**Screenshots or Logs**
```
_____________________________________________________________________
WARNING! Your environment specifies an invalid locale.
 The unknown environment variables are:
   LC_CTYPE=UTF-8 LC_ALL=
 This can affect your user experience significantly, including the
 ability to manage packages. You may install the locales by running:

   sudo apt-get install language-pack-UTF-8
     or
   sudo locale-gen UTF-8

To see all available language packs, run:
   apt-cache search "^language-pack-[a-z][a-z]$"
To disable this message for all users, run:
   sudo touch /var/lib/cloud/instance/locale-check.skip
_____________________________________________________________________
```

### PR DESCRIPTION
**Pull request by thenishantsapkota**
# Pull Request

## Related issue
Fixes #62 

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [ x ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ x ] Have you read the contributing guidelines?
- [ x ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by thenishantsapkota** [comment]
@alallema I think my PR fixes the issue
Please review it!

**Comment by alallema** [comment]
>@alallema I think my PR fixes the issue
Please review it!

I will do it as soon as I have time to try it and review it.

**Comment by alallema** [comment]
Hi @thenishantsapkota,
Thanks for your PR!
On the other hand, I have just checked and this exit does not exist anymore, unfortunately, I am really sorry it is my fault I did not update this exit. However, I still put you the tag `hacktoberfest-accepted`.
Thanks again for contributing with Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some swag from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Comment by alallema** [comment]
_This message is sent automatically_

Thanks again for contributing to Meilisearch :heart:
If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some gift from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Comment by thenishantsapkota** [comment]
Hi @alallema 
Am I still eligible for Hacktoberfest swag from Meilisearch?

**Comment by alallema** [comment]
@thenishantsapkota yes of course!

**Pull request closed without merging**
